Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # plot
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator plot/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/plot.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/plot.py", line 47, in on_event
[
          [
  FFFFFFFF380200001000000000000A000C000600050008000A000000000104000C0000000800080000000400080000000400000001000000040000003CFEFFFF0000010C140000001C0000000400000001000000140000000500000068616E64730000008CFFFFFF68FEFFFF0000010D2000000028000000040000000400000020010000F0000000B400000014000000040000006974656D00000000C4FFFFFFA0FEFFFF0000010C1400000030000000040000000100000028000000140000006E6F726D616C697A65645F6C616E646D61726B73000000000400040004000000E0FEFFFF00000110140000001C000000040000000100000018000000040000006974656D0000000016FFFFFF0300000010FFFFFF0000010310000000180000000400000000000000040000006974656D0000000002FFFFFF000001003CFFFFFF00000102100000002000000004000000000000000600000068616E646564000008000C000800070008000000000000010800000074FFFFFF000001031000000018000000040000000000000004000000666C61670000000066FFFFFF00000100A0FFFFFF00000110140000001800000004000000010000001400000003000000626F7800D2FFFFFF02000000CCFFFFFF00000110140000002000000004000000010000002C000000040000006974656D00000600080004000600000004000000100014000800060007000C00000010001000000000000103100000001C0000000400000000000000040000006974656D00000600080006000600000000000100FFFFFFFFF801000014000000000000000C0016000600050008000C000C0000000003040018000000400100000000000000000A0018000C00040008000A0000001C01000010000000010000000000000000000000100000000000000000000000000000000000000000000000000000000800000000000000080000000000000000000000000000000800000000000000000000000000000008000000000000000000000000000000080000000000000000000000000000000800000000000000200000000000000028000000000000000000000000000000280000000000000004000000000000003000000000000000000000000000000030000000000000000100000000000000380000000000000000000000000000003800000000000000080000000000000040000000000000000000000000000000400000000000000000000000000000004000000000000000FC00000000000000000000000A0000000100000000000000000000000000000001000000000000000000000000000000010000000000000000000000000000000200000000000000000000000000000008000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000001000000000000000000000000000000150000000000000000000000000000003F00000000000000000000000000000000000000010000001ABD2243C0D818437A6A99434D78944342751A438E4695439C592443BB389A43C660943C0000000000000000000000000000000015000000246263436E7F8743705AA837BA5154436A2C76432224D63C7AFE5143A78A64438D462A3D98CB5343281B57438822513DBD3657438CF54E43C6325A3D39895A4302C9594304D9B13CB0105C43080348438CA8A83C066E5B43CCBF4743449C733CDDBA5943D01E4B431C9A793C73B26343DA115B435845D73B42BA6443FA81474378F9853BE84E64434C48484380BB12B90E0162430ACE4D43808C0DBA3E936C43CC775D434AC3CCBBA1546D439E324B43866795BCF4706C4310B94B4376C3B3BC9BF46A4356195143CEBDABBC9E347543372A6143D60F8CBCFC0177431B0B51435982BDBC7DBF7543A53F4D43B57CB2BCF6CF734357C84E43D04098BC00000000FFFFFFFF00000000

]
      ValueError: not enough values to unpack (expected 6, got 1)

Location:
    binaries/runtime/src/operator/python.rs:29:9
