Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # plot
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator plot/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/plot.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/plot.py", line 51, in on_event
[[{'box': [[83.51319122314453, 182.05064392089844, 164.47364807128906, 263.0111083984375], [214.0863494873047, 295.04681396484375, 115.54888916015625, 196.5093536376953]], 'flag': 0.9979946613311768, 'handed': 0, 'landmarks': [[194.4383544921875, 242.23593139648438, 2.471345942467451e-05], [188.74908447265625, 225.0018310546875, 0.003009573556482792], [180.0213623046875, 210.04971313476562, 0.00716320239007473], [171.26455688476562, 202.36483764648438, 0.008035263046622276], [162.2229766845703, 197.06304931640625, 0.010117659345269203], [179.530029296875, 196.65322875976562, 0.02152642421424389], [165.62548828125, 183.97406005859375, 0.03137357905507088], [156.09619140625, 180.7235870361328, 0.029302503913640976], [148.8441619873047, 179.25685119628906, 0.026243986561894417], [175.06845092773438, 201.403076171875, 0.015388121828436852], [156.89532470703125, 189.34548950195312, 0.019978974014520645], [145.9248046875, 190.80520629882812, 0.009298499673604965], [139.27052307128906, 193.06991577148438, -0.004966352134943008], [170.40283203125, 208.13275146484375, 0.008199730888009071], [152.88735961914062, 198.18582153320312, 0.004743006080389023], [148.81661987304688, 201.69305419921875, -0.007169099524617195], [148.8575897216797, 205.84678649902344, -0.01608184352517128], [165.75323486328125, 216.27407836914062, 0.00189303420484066], [151.2341766357422, 209.43048095703125, 0.0014592893421649933], [146.44033813476562, 210.0080108642578, -0.0006356984376907349], [144.81076049804688, 211.06674194335938, -0.005081054754555225]]}, {'box': [[661.5325317382812, 435.4841613769531, 500.6753845214844, 274.62701416015625], [362.18121337890625, 201.3240966796875, 588.2295532226562, 427.3724365234375]], 'flag': 0.025990623980760574, 'handed': 0, 'landmarks': [[454.9220886230469, 385.20330810546875, 2.615925041027367e-05], [473.0458984375, 384.53045654296875, -0.07644949108362198], [479.16217041015625, 383.1591796875, -0.13276967406272888], [483.2994689941406, 384.2884521484375, -0.17018458247184753], [484.13238525390625, 385.40960693359375, -0.20506638288497925], [460.0902099609375, 381.77886962890625, -0.22213824093341827], [455.8936462402344, 384.44451904296875, -0.303089439868927], [449.1767883300781, 381.0868835449219, -0.34596550464630127], [443.23760986328125, 380.34698486328125, -0.37398526072502136], [433.89410400390625, 375.6084899902344, -0.2087719887495041], [417.67852783203125, 366.684326171875, -0.31099069118499756], [404.96221923828125, 365.7698669433594, -0.3617739975452423], [395.1168212890625, 372.11981201171875, -0.40464264154434204], [411.4765930175781, 369.6624450683594, -0.19014033675193787], [390.52117919921875, 359.04364013671875, -0.2718077301979065], [383.92352294921875, 358.102294921875, -0.3065433204174042], [376.80548095703125, 363.6184387207031, -0.3329010605812073], [397.72283935546875, 367.2892150878906, -0.1725587397813797], [377.5567626953125, 357.55328369140625, -0.2241789847612381], [372.8438720703125, 355.62701416015625, -0.25485455989837646], [370.43341064453125, 359.2029113769531, -0.2812718451023102]]}]]
          landmarks = np.array(hand['landmarks'])
1

      TypeError: list indices must be integers or slices, not str

Location:
    binaries/runtime/src/operator/python.rs:29:9
