Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # plot
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator plot/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/plot.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/plot.py", line 51, in on_event
{'box': [[326.47344970703125, 241.05697631835938, 380.1464538574219, 294.72998046875], [188.19485473632812, 241.8678436279297, 273.611328125, 327.2843322753906]], 'flag': 0.0062550208531320095, 'handed': 0, 'normalized_landmarks': [[285.96661376953125, 273.6778869628906, 2.1180370822548866e-05], [297.011474609375, 267.0657958984375, 0.007044900208711624], [307.0998840332031, 260.2375183105469, 0.01024002954363823], [315.1712951660156, 255.41720581054688, 0.01371791772544384], [322.59576416015625, 251.4278106689453, 0.011995152570307255], [314.40582275390625, 257.4113464355469, -0.012991570867598057], [326.86944580078125, 250.37673950195312, -0.003514699637889862], [332.0552673339844, 246.8234100341797, 0.009136654436588287], [334.8058166503906, 244.19017028808594, 0.024090437218546867], [312.633056640625, 256.97283935546875, -0.0053369998931884766], [326.0809020996094, 250.49530029296875, 0.0074932761490345], [330.2791442871094, 247.27468872070312, 0.02189229242503643], [332.38397216796875, 245.7264404296875, 0.03330564498901367], [309.8831787109375, 257.2853088378906, 0.005983555689454079], [321.30126953125, 252.13665771484375, 0.01898624561727047], [324.2689208984375, 249.58316040039062, 0.03128543496131897], [324.95367431640625, 249.28219604492188, 0.04150852933526039], [306.6330871582031, 257.863037109375, 0.018285779282450676], [316.28631591796875, 254.34603881835938, 0.032592397183179855], [319.16412353515625, 252.28057861328125, 0.04264155030250549], [319.9959411621094, 251.90602111816406, 0.0517808198928833]]}
          hand = hand[0]

      KeyError: 0

Location:
    binaries/runtime/src/operator/python.rs:29:9
